import {useEffect,useState} from "react";
import api from "../services/api";
import PageHeader from "../components/PageHeader";
import StatusBadge from "../components/StatusBadge";
import {errorMessage,listFrom,formatDateTime} from "../utils/data";
import {useAuth} from "../context/AuthContext";

export default function Admissions(){
 const {user}=useAuth();const[rows,setRows]=useState([]),[beds,setBeds]=useState([]),[form,setForm]=useState({patientId:"",doctorId:"",bedId:""}),[show,setShow]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const canCreate=["ADMIN","DOCTOR","NURSE"].includes(user?.role),canDischarge=["ADMIN","DOCTOR","NURSE"].includes(user?.role);
 const load=async()=>{try{const[a,b]=await Promise.all([api.get("/admissions"),api.get("/beds?status=AVAILABLE")]);setRows(listFrom(a.data,["admissions"]));setBeds(listFrom(b.data,["beds"]))}catch(e){setError(errorMessage(e,"Unable to load admissions."))}};useEffect(()=>{load()},[]);
 const submit=async e=>{e.preventDefault();try{await api.post("/admissions",{patientId:Number(form.patientId),doctorId:Number(form.doctorId),bedId:Number(form.bedId)});setSuccess("Patient admitted and bed assigned.");setForm({patientId:"",doctorId:"",bedId:""});setShow(false);load()}catch(e){setError(errorMessage(e,"Unable to admit patient."))}};
 const discharge=async id=>{if(!confirm("Discharge this patient?"))return;try{await api.patch(`/admissions/${id}/discharge`);setSuccess("Patient discharged and bed released.");load()}catch(e){setError(errorMessage(e,"Unable to discharge patient."))}};
 return <div><PageHeader title="Admissions" subtitle="Inpatient admission, bed assignment and discharge" action={canCreate&&<button className="primary-button" onClick={()=>setShow(true)}>+ Admit Patient</button>}/>{error&&<div className="alert error">{error}</div>}{success&&<div className="alert success">{success}</div>}
 {show&&<div className="panel"><form className="form-grid" onSubmit={submit}><label>Patient ID *<input type="number" value={form.patientId} onChange={e=>setForm({...form,patientId:e.target.value})} required/></label><label>Doctor ID *<input type="number" value={form.doctorId} onChange={e=>setForm({...form,doctorId:e.target.value})} required/></label><label>Available Bed *<select value={form.bedId} onChange={e=>setForm({...form,bedId:e.target.value})} required><option value="">Select bed</option>{beds.map(b=><option key={b.id} value={b.id}>{b.bedNumber} — {b.ward?.name||`Ward ${b.wardId}`}</option>)}</select></label><div className="form-actions full"><button type="button" className="secondary-button" onClick={()=>setShow(false)}>Cancel</button><button className="primary-button">Admit Patient</button></div></form></div>}
 <div className="panel"><div className="table-wrap"><table><thead><tr><th>ID</th><th>Patient</th><th>Doctor</th><th>Ward / Bed</th><th>Admitted</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td>#{a.id}</td><td>{a.patient?.patientCode||a.patientId}</td><td>{a.doctor?.user?.name||a.doctorId}</td><td>{a.bed?.ward?.name||a.bed?.wardId||"—"} / {a.bed?.bedNumber||a.bedId}</td><td>{formatDateTime(a.admissionDate)}</td><td><StatusBadge value={a.status}/></td><td>{a.status==="ADMITTED"&&canDischarge&&<button className="small-button danger" onClick={()=>discharge(a.id)}>Discharge</button>}</td></tr>)}</tbody></table></div></div></div>
}
