import {useEffect,useState} from "react";
import api from "../services/api";
import PageHeader from "../components/PageHeader";
import {errorMessage,listFrom,formatDateTime} from "../utils/data";
import {useAuth} from "../context/AuthContext";

const blank={patientId:"",nurseId:"",temperature:"",bloodPressure:"",heartRate:"",respiratoryRate:"",oxygenSaturation:"",weight:""};
export default function Vitals(){
 const {user}=useAuth();const[rows,setRows]=useState([]),[form,setForm]=useState(blank),[show,setShow]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const canCreate=["ADMIN","NURSE"].includes(user?.role);
 const load=async()=>{try{const{data}=await api.get("/vitals");setRows(listFrom(data,["vitals"]))}catch(e){setError(errorMessage(e,"Unable to load vitals."))}};useEffect(()=>{load()},[]);
 const submit=async e=>{e.preventDefault();try{const numeric=["patientId","nurseId","heartRate","respiratoryRate"];const payload={...form};numeric.forEach(k=>{if(payload[k]!=="")payload[k]=Number(payload[k])});["temperature","oxygenSaturation","weight"].forEach(k=>{if(payload[k]!=="")payload[k]=Number(payload[k])});if(!payload.nurseId)delete payload.nurseId;await api.post("/vitals",payload);setSuccess("Vitals recorded.");setForm(blank);setShow(false);load()}catch(e){setError(errorMessage(e,"Unable to record vitals."))}};
 return <div><PageHeader title="Vitals" subtitle="Patient vital sign records" action={canCreate&&<button className="primary-button" onClick={()=>setShow(true)}>+ Record Vitals</button>}/>{error&&<div className="alert error">{error}</div>}{success&&<div className="alert success">{success}</div>}
 {show&&<div className="panel"><form className="form-grid" onSubmit={submit}><label>Patient ID *<input type="number" value={form.patientId} onChange={e=>setForm({...form,patientId:e.target.value})} required/></label><label>Nurse ID<input type="number" value={form.nurseId} onChange={e=>setForm({...form,nurseId:e.target.value})}/></label><label>Temperature<input type="number" step="0.1" value={form.temperature} onChange={e=>setForm({...form,temperature:e.target.value})}/></label><label>Blood Pressure<input value={form.bloodPressure} onChange={e=>setForm({...form,bloodPressure:e.target.value})} placeholder="120/80"/></label><label>Heart Rate<input type="number" value={form.heartRate} onChange={e=>setForm({...form,heartRate:e.target.value})}/></label><label>Respiratory Rate<input type="number" value={form.respiratoryRate} onChange={e=>setForm({...form,respiratoryRate:e.target.value})}/></label><label>Oxygen Saturation<input type="number" step="0.1" value={form.oxygenSaturation} onChange={e=>setForm({...form,oxygenSaturation:e.target.value})}/></label><label>Weight<input type="number" step="0.1" value={form.weight} onChange={e=>setForm({...form,weight:e.target.value})}/></label><div className="form-actions full"><button type="button" className="secondary-button" onClick={()=>setShow(false)}>Cancel</button><button className="primary-button">Save Vitals</button></div></form></div>}
 <div className="panel"><div className="table-wrap"><table><thead><tr><th>Patient</th><th>Temp</th><th>BP</th><th>HR</th><th>RR</th><th>O₂</th><th>Weight</th><th>Recorded</th></tr></thead><tbody>{rows.map(v=><tr key={v.id}><td>{v.patient?.patientCode||v.patientId}</td><td>{v.temperature??"—"}</td><td>{v.bloodPressure||"—"}</td><td>{v.heartRate??"—"}</td><td>{v.respiratoryRate??"—"}</td><td>{v.oxygenSaturation??"—"}</td><td>{v.weight??"—"}</td><td>{formatDateTime(v.recordedAt)}</td></tr>)}</tbody></table></div></div></div>
}
